### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by corvinalive** [SergeySatskiy/cdm-flowparser#4]
Здравствуйте.
Прочитал вашу статью на Хабре. Мне очень понравилась ваша идея.
Моя система Ubuntu 16.04 32bit, python 2.7.12. 
Хотел скомпилировать, при компиляции выдает ошибки вида:
`In file included from thirdparty/pycxx/CXX/Objects.hxx:40:0,
                 from src/cflowfragments.hpp:29,
                 from src/cflowfragments.cpp:28:
thirdparty/pycxx/CXX/Python2/Objects.hxx:1958:21: 
note: 
candidate: 
	std::__cxx11::string Py::String::as_std_string(const char*, const char*) const
	std::string as_std_string( const char *encoding, const char *error="strict" ) const;
                     ^
thirdparty/pycxx/CXX/Python2/Objects.hxx:1958:21:
note:
   candidate expects 2 arguments, 0 provided
src/cflowfragments.cpp: In member function ‘Py::Object ExceptPart::getDisplayValue(const Py::Tuple&)’:
src/cflowfragments.cpp:3309:73: 
error: no matching function for call to ‘Py::String::as_std_string()’
                 std::string  buf( Py::String( args[ 0 ] ).as_std_string() );
                                                                         ^`

Подскажите, что можно сделать.

**Comment by SergeySatskiy** [comment]
А вы исходный текст брали с master?
Если да, то попробуйте пожалуйста взять исходный текст, соответствующий релизу 1.0.1. Архив есть на вкладке с релизами.

**Comment by corvinalive** [comment]
Код с релиза 1.0.1 скомпилировался успешно. Спасибо, буду пробовать.

**Comment by SergeySatskiy** [comment]
Значит, скорее всего, это моя ошибка - при портировании на питон 3 я, видимо, один из коммитов сделал по ошибке на master, а не на p3.
Прошу прощения.
