### ISSUE TITLE
Не собирается с исходников

### ISSUE THREAD

**Issue by yevhenjl** [SergeySatskiy/cdm-flowparser#6]
`
cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make all
cd .. && CDM_PROJECT_BUILD_VERSION= python setup.py build_ext --inplace
  File "setup.py", line 53
    'README.md convertion to rst failed', file=sys.stderr)
                                              ^
SyntaxError: invalid syntax
make[1]: *** [all] Error 1
make: *** [all] Error 2
`

MacOS Sierra, python 3.6

**Comment by SergeySatskiy** [comment]
А виртуальное окружение python 3.6 активировано? Что выдаст просто запуск питона?
```
python
```
Такое впечатление, что запускается питон 2, который не понимает синтаксиса питон 3.

**Comment by yevhenjl** [comment]
venv не активирован. На компьютере есть и python 2 и python 3.
С исходников все ломается на make.
Не устанавливается и с командой `pip3 install cdmcfparser`.

**Comment by SergeySatskiy** [comment]
А вы следуете инструкциям с этой странички http://codimension.org/download/linuxdownload.html ?

Надо создать новое виртуальное окружение с питон 3,  активировать его и потом выполнять `pip3 install ...` Иначе заголовочные файлы нужной версии питона не будут найдены, нужные библиотеки не будут найдены и т.п.

`make` тоже надо запускать с активированным виртуальным окружением, так как он работает через setup.py, который написан на питон 3.

**Comment by yevhenjl** [comment]
Нет, я эту страницу не читал. Сейчас все сделаю. По результатам отпишусь.

**Comment by SergeySatskiy** [comment]
Since there are no more reports of building from sources... closing.
