### ISSUE TITLE
Support for Python 3.9?

### ISSUE THREAD

**Issue by dgarijo** [SergeySatskiy/cdm-flowparser#7]
Hello,
we have been using `cdmcfparser` in one of our projects, but just found out that for Python 3.9.+ the library fails for most Python files we process.

The error is just: `Segmentation fault (core dumped)` when using `getControlFlowFromFile(self.path)` in `cdmcfparser.py`.

The same function returns correctly for the same files in Python 3.7 and Python 3.8.

Is support for Python 3.9 planned? 

Thanks in advance!

**Comment by dgarijo** [comment]
I have noticed that while the latest version released is 3.3.2, for Python 3.9 it is 2.2.3.

**Comment by SergeySatskiy** [comment]
This kind of error basically means that there are changes in the python grammar comparing to the previous version. Most likely it would take quite a bit of efforts to cover the new grammar. I had such experience with older versions.

I mostly use codimension IDE (for which I developed cdmcfparser) at work and we still use python 3.8. I was thinking about looking into support of 3.9 however I do not have any ETA. I may have some time this weekend to look at what adjustments are required but I cannot promise anything.

Out of curiosity, what for are you using cdmcfparser? I developed it specifically for codimension IDE and did not expect someone else would use it. I thought the other simpler parser (cdmpyparser) would be more interesting for general public.

**Comment by dgarijo** [comment]
@SergeySatskiy,
ouch, I hope no big changes are needed.
And absolutely, I understand not having an ETA. There is no rush at all! 

As for your question, we are building a framework for retrieving different insights from Python repositories (https://github.com/SoftwareUnderstanding/inspect4py), and we wanted to have a control-flow view of each file in a code repository. We have played around with a few, but we found your representation easy to use and understand.

**Comment by SergeySatskiy** [comment]
Last night I briefly looked at what exactly caused the problem. It turned out they have changed the decorators grammar in 3.9.
The change affects the AST significantly. I have some ideas of what needs to be done though.

**Comment by SergeySatskiy** [comment]
@dgarijo 
Release 2.4.0 with python 3.9 support has been published on pypi. Please give it a try and let me know if it works for you.
My tests have passed however it would be nice if you try it too in your environment.
Thanks!

**Comment by dgarijo** [comment]
Thanks! I will give it a try this week.

**Comment by SergeySatskiy** [comment]
Since there is no feedback for a while I assume that there are no problems with python 3.9 support.
Thus I am closing the issue.

**Comment by dgarijo** [comment]
@SergeySatskiy,
sorry, it's been extremely busy. I am happy to have the issue closed, I will reopen if necessary. Thanks again!
